#!/bin/bash


_dir=$(dirname "${_me}")


# if [ ! -d "${_venv}" ]; then
#     echo "venv is missing, run make"
#     exit 1
# fi

# source "${_venv}/bin/activate"
exec "python" "_python/pgbench_python.py" $@
